version: '3.8'

services:
  api-server:
    build: .
    container_name: api-server
    ports:
      - "8081:8081"
    volumes:
      # Mount auth directory to persist tokens
      - ./auth:/app/auth
      # Mount API type directories for development (optional)
      - ./apis:/app/apis
      # Mount local-data directory for Files API
      - ./local-data:/app/local-data
      # Mount main server file for development
      - ./api_server.py:/app/api_server.py
      - ./base_api.py:/app/base_api.py
      # Mount WhatsApp Chrome profile for persistent sessions
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome
      - CHROME_PATH=/usr/bin/google-chrome
    restart: unless-stopped
    # Enable GUI support for WhatsApp Web
    privileged: true
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
